vich_uploader:
    db_driver: orm

    mappings:
        annonce:
            uri_prefix: /public/images/
            upload_destination: '%kernel.project_dir%/public/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
